### ISSUE TITLE
Packet scrambling?

### ISSUE THREAD

**Issue by Sonicmaster13** [xzfc/agar-expose#32]
From my research, the packets appear to be scrambled, as in every different packet that i send is not the same. The init packets appear to be the same, the 2nd changing every hour. But the other packets, such as MoveTo and facebook login, appear to be different every time. explanation: one time the facebook login packet might be 34 and the next time you login the packet is 71. I do not think it is possible to guess which packet will be the next packet, but if you can see some packet similarities between connections you might be able to detect if at least 1 packet is always received that might contain some important info.
 -Mr.Sonic Master

**Comment by ghost** [comment]
Fake Sonic, the real one dosent have that name

**Comment by MasonBurdette** [comment]
@xtremeplayzcode nah that's him ur fake for faking agario protocol shit.

**Comment by mayed505** [comment]
@XtremePlayzCODE lol

**Comment by ghost** [comment]
I don't fake protocol stuff.

**Comment by Barbosik** [comment]
messages are encrypted, and a key is changed on every outgoing message.
Sometimes (rarely) server lost right key and it leads to the bug when your cell starts to split and eject randomly. It's server bug. I'm not sure why it happens. I think it's because some packet lost at transport level and after that server cannot decrypt client messages anymore. It happens in vanilla client, you can read about this bug on reddit. But it happens very rarely, so it can be ignored. But it's nasty bug for the player, because he will lost control and will need to reconnect.

**Comment by MasonBurdette** [comment]
@Barbosik how did you discover the key?

**Comment by Barbosik** [comment]
**MasonBurdette**: it's a secret :) If I reveal it, it will be used by botters and they will change it again.
But I can hint. You can use basic cryptography in order to get the key, you even don't need to look into core.js. It's easy puzzle, at least I get it without looking into source at the same day when they released protocol 7 ;)

**Comment by ZfsrGhS953** [comment]
I think I found out how to decrypt the world border packet:
1. Make sure the packet is 40 bytes long. Otherwise it can’t be the border packet.
2. XOR 33 and the second byte of the packet. Now we have the bytes 2-4 of encryption key in the 2nd to 4th byte, and
byte 1 of the encryption key in byte 5.
3. Now apply the decryption XOR the encryption key with bytes 1-4, 5-8, 9-12, etc until you get to bytes 37-40
4. Byte 1 must be 255 and byte 8 must be 64, otherwise it isn’t the border packet.
Now remove the first 7 bytes and you got a normal border packet like in protocol 5.

**Comment by ghost** [comment]
Thanks for the world border packet decryption tutorial @ZfsrGhS953

**Comment by ZfsrGhS953** [comment]
I'm not sure about it yet, try it and tell if it works.

**Comment by ghost** [comment]
Too busy doing other stuff. Try it yourself

**Comment by Barbosik** [comment]
**ZfsrGhS953**: I was used the same approach :) But there is no need to calculate the key. You can get the key from message 0xF1, it is xored but I think you will find how. But the key is changed after each clear message 0x12

**Comment by ZfsrGhS953** [comment]
To get the key, bytes of packet 255 get xored with bytes of packet 241. I don't understand how it's changed after 18, but anyway, for bots only getting the world border packet is needed, and send the move packet, eject and split packet. The sent packets appear to be either encrypted with two keys, or the coordinates are being scrambled by a very large number(both x and y have been very large numbers in the hundreds of millions in packets I decrypted. You can get the 1st byte of the key from the packet's last byte, and bytes 2-4 from the bytes before it. By the way, Bаgаr.IO already is close to working, so we need make free bots before they start getting money.

**Comment by Barbosik** [comment]
you cannot use bots, because if you start to use it, they will change protocol. It's just a question for 1-2 hours. Do you really need to work hard on reverse to play with bots for 1-2 hours and then to start reverse from scratch again? I don't think so. 
So, please don't use bots. Because you will ruin alternative clients in such way.

**Comment by ZfsrGhS953** [comment]
They can't just "change" it in 2 hours. It requires at least a day because if you just make a new protocol and remove support for old one, clients that didn't refresh the page will not work anymore and they don't know what to do.

**Comment by Barbosik** [comment]
they already have it. And there is a message from server in the protocol, to reload client.

**Comment by ZfsrGhS953** [comment]
Then there make bots by completely loading agar.io(with all html, css, canvas etc) and grabbing variables from JS(world border decrypted) and writing them back(for mouse,eject,split). It will be more CPU consuming, though

**Comment by Barbosik** [comment]
**ZfsrGhS953**: you don't understand. If any kind of mass bot will appear they will change code just in several hours, it's pretty easy. And I will need to modify key parser in my client. 
Don't do that, please. You will not be able to play with bots more than 1-2 hours in any case, but alternative clients will be ruined again.

**Comment by ZfsrGhS953** [comment]
Change code? And what will that do to stop the way I mentioned before?

**Comment by MasonBurdette** [comment]
Would it be possible to run agario.core.js externally and simulate mouse movements?

**Comment by Barbosik** [comment]
just a small change and all your hooks will be ruined. Because variables will be changed and you will not be able to read or change it. Encryption will be changed, so you will not be able to decrypt and encrypt messages.

Mass bots affects their servers performance, so they will be notified about your bots just in second when you will start to use it. And they will fix it very quickly. Because it ruins the game.

If you're using it just for mods and extensions, it will not affects their servers, so it's ok.

**Comment by ZfsrGhS953** [comment]
1-2 hours? Impossible, when they change protocol and upload new server version it will still take around 3 hours for the servers to restart and get the updated version. And when they released the protocol 6 update, some bot site named "СlientM.рw" was fixed 10 May and worked for a WEEK until 17 May when they released protocol 7. So I disagree that they fix it in 10 minutes. And mass feeding bots don't affect server performance a lot, they have very small viewing range due to their low mass (10-129). I spent about 2 hours for reversing. It's not a DDoS attack either.

**Comment by Barbosik** [comment]
So, you're working on bots just to play 3 hours and then move all your work into trash? Because after update all your bot code will not works again and you will need to start research from scratch.
Is it really matter - how much time is needed for update? 2 hours or 3 hours.. What is the difference? After update all your work will be just a trash.

You're talking that mass bot doesn't affect server performance? Are you crazy?
Each bot add 1 new connection. If there are 10 players on the server and each of them using 1000 bots, the server will need to handle additional 10000 connections! 
Do you really think that additional 10000 connections will not affect the server performance?

But even more. Each additional player needs increase calculations complexity for collision detector in geometric progression. It means that for 10 bots server cpu load will be 100 times higher. For 100 bots cpu load will be 10000 times higher. For 10000 bots, cpu load will be 100000000 times higher.

Mass bots much worse than DDoS attack, because DDoS attack makes high load just on network. But mass bots makes high load on network and on server CPU. 

You're right, it doesn't affect server performance, it just kill servers with exterme overload.

**Comment by hassanila** [comment]
Ok ok

**Comment by Barbosik** [comment]
in general, I do not care. If someone so stupid to make bots, he should make it. After update he will be learned. And if he still not reversed so easy protection, I'm sure that he will be completely unable to reverse anything after update.

**Comment by MrSonicMaster** [comment]
@XtremePlayzCODE No, that was me, its my other account

**Comment by ZfsrGhS953** [comment]
I only said that the bots wouldn't affect performance A LOT. Of course, any connection will affect performance. As for the collision, it will increase linearly, not QUADratically because agar.io uses QUADtrees. That means for each cells it only checks for cells that are near(how near depends on quadtree depth) And universal zoom may be possible with a browser modification that reduces scale of all canvases.

**Comment by ghost** [comment]
@MrSonicMaster kk sorry

**Comment by ZfsrGhS953** [comment]
Bаgаr.IО has started working. Now let's see if they can fix it in 3 hours.

**Comment by MasonBurdette** [comment]
@ZfsrGhS953 still working... :D

**Comment by ZfsrGhS953** [comment]
I think this function encrypts packets and send them to the server:
`
{

```
        function Uc(b) { b = b >> 0;
        var d = 0
          , e = 0
          , f = 0
          , g = 0
          , h = 0
          , j = 0;
        g = i;
        i = i + 32 >> 0;
        e = g + 16 >> 0;
        f = g;
        c[e >> 2] = 0;
        c[e + 4 >> 2] = 0;
        c[e + 8 >> 2] = 0;
        d = e + 8 >> 0;
        j = dg(1) >> 0;
        h = j + 1 >> 0;
        a[j >> 0] = -2;
        c[e + 4 >> 2] = j;
        c[d >> 2] = h;
        c[e + 12 >> 2] = h;
        Vc(e, 8);
        e = e + 4 >> 0;
        h = c[e >> 2] >> 0;
        ic(b, h, (c[d >> 2] >> 0) - h >> 0);
        e = c[e >> 2] >> 0;
        if (e) {
            if ((c[d >> 2] >> 0) != (e >> 0))
                c[d >> 2] = e;
            fg(e)
        }
        if (!(a[13840] >> 0))
            d = 0;
        else
            d = td() >> 0;
        c[f >> 2] = 0;
        c[f + 4 >> 2] = 0;
        c[f + 8 >> 2] = 0;
        e = f + 8 >> 0;
        h = dg(1) >> 0;
        j = h + 1 >> 0;
        a[h >> 0] = -1;
        c[f + 4 >> 2] = h;
        c[e >> 2] = j;
        c[f + 12 >> 2] = j;
        Vc(f, d);
        j = f + 4 >> 0;
        h = c[j >> 2] >> 0;
        ic(b, h, (c[e >> 2] >> 0) - h >> 0);
        c[b + 40 >> 2] = d ^ 673720360;
        a[b + 36 >> 0] = 1;
        d = c[j >> 2] >> 0;
        if (!d) {
            mb(40);
            i = g;
            return
        }
        if ((c[e >> 2] >> 0) != (d >> 0))
            c[e >> 2] = d;
        fg(d);
        mb(40);
        i = g;
        return
    }
```

`

**Comment by Barbosik** [comment]
**ZfsrGhS953:** you're wrong, it's decrypt key generator

**Comment by MasonBurdette** [comment]
Currently I'm working on just running agario.core.js by itself (with hooks). Then use some core functions for movement and split/eject.

**Comment by ZfsrGhS953** [comment]
@MasonBurdette , but keep in mind that it will be more CPU consuming. Run separate node.js for each bot and have them connect to a master server which broadcasts the mouse position, eject and split commands. That's how I fixed lag problem when bots were not patched: I set the bots per ip limit to 1 and ran 3 bot servers. That means 3 threads and 3 bots per IP.
@Barbosik , then what is this? Maybe you're wrong because I replaced | with >> in the code above(and this one)? I did that so that you could paste the function straight into agario-client(2) without much effort. If it doesn't work, add ()

e = c[p >> 2] >> 0;
                        f = c[q >> 2] >> 0;
                        if (((a[13825] >> 0) != 0 ? (a[n >> 0] >> 0) != 0 : 0) ? (g = nd() >> 0,
                        c[r >> 2] = c[o >> 2] ^ g,
                        (f >> 0) != 0) : 0) {
                            g = 0;
                            do {
                                t = e + g >> 0;
                                a[t >> 0] = a[t >> 0] ^ a[r + (g & 3) >> 0];
                                g = g + 1 >> 0
                            } while ((g >> 0) != (f >> 0))
                        }
                        e = c[p >> 2] >> 0;
                        f = c[q >> 2] >> 0;
                        if ((f >> 0) != 0 ? (c[r >> 2] = e,
                        c[j >> 2] = f,
                        c[l >> 2] = 1,
                        k = c[(c[m >> 2] >> 0) + ((d[e >> 0] >> 0) \* 24 >> 0) + 16 >> 2] >> 0,
                        (k >> 0) != 0) : 0) {
                            tb[c[(c[k >> 2] >> 0) + 24 >> 2] & 127](k, r);
                            e = c[p >> 2] >> 0
                        }
                        li(e);

**Comment by Barbosik** [comment]
ZfsrGhS953: I just found this function in my analysis notes, I was marked it as decryption key generator. I didn't added other comments for this function, because this function is not important for encryption/decryption/authentication, so I didn't analysed it. 
But this is definitely not a place where outgoing message is encrypted. Because there is another function with 3 arguments which doing it for all outgoing messages, I analysed it very well, and know all details, so I'm sure that your finding is wrong. Sorry, but I cannot share this info, because I don't want to help for botters.

**Comment by ZfsrGhS953** [comment]
With three arguments? This one seems to be it. I won't replace | this time! Replace it yourself, Mr. Botter-Hater!
function Hd(a, b, d) {
            a = a | 0;
            b = b | 0;
            d = d | 0;
            var e = 0
              , f = 0
              , h = 0
              , i = 0.0
              , j = 0
              , k = 0
              , l = 0.0
              , m = 0
              , n = 0
              , o = 0
              , p = 0
              , q = 0.0;
            switch (b - a >> 2 | 0) {
            case 2:
                {
                    d = b + -4 | 0;
                    e = c[d >> 2] | 0;
                    f = c[a >> 2] | 0;
                    if (!(+g[e + 20 >> 2] < +g[f + 20 >> 2])) {
                        a = 1;
                        return a | 0
                    }
                    c[a >> 2] = e;
                    c[d >> 2] = f;
                    a = 1;
                    return a | 0
                }
            case 3:
                {
                    k = a + 4 | 0;
                    h = b + -4 | 0;
                    e = c[k >> 2] | 0;
                    j = c[a >> 2] | 0;
                    l = +g[e + 20 >> 2];
                    i = +g[j + 20 >> 2];
                    f = c[h >> 2] | 0;
                    d = +g[f + 20 >> 2] < l;
                    if (!(l < i)) {
                        if (!d) {
                            a = 1;
                            return a | 0
                        }
                        c[k >> 2] = f;
                        c[h >> 2] = e;
                        d = c[k >> 2] | 0;
                        e = c[a >> 2] | 0;
                        if (!(+g[d + 20 >> 2] < +g[e + 20 >> 2])) {
                            a = 1;
                            return a | 0
                        }
                        c[a >> 2] = d;
                        c[k >> 2] = e;
                        a = 1;
                        return a | 0
                    }
                    if (d) {
                        c[a >> 2] = f;
                        c[h >> 2] = j;
                        a = 1;
                        return a | 0
                    }
                    c[a >> 2] = e;
                    c[k >> 2] = j;
                    d = c[h >> 2] | 0;
                    if (!(+g[d + 20 >> 2] < i)) {
                        a = 1;
                        return a | 0
                    }
                    c[k >> 2] = d;
                    c[h >> 2] = j;
                    a = 1;
                    return a | 0
                }
            case 4:
                {
                    p = a + 4 | 0;
                    o = a + 8 | 0;
                    n = b + -4 | 0;
                    j = c[p >> 2] | 0;
                    f = c[a >> 2] | 0;
                    q = +g[j + 20 >> 2];
                    i = +g[f + 20 >> 2];
                    d = c[o >> 2] | 0;
                    l = +g[d + 20 >> 2];
                    h = l < q;
                    e = j;
                    k = d;
                    m = f;
                    do
                        if (q < i) {
                            if (h) {
                                c[a >> 2] = k;
                                c[o >> 2] = m;
                                e = m;
                                break
                            }
                            c[a >> 2] = e;
                            c[p >> 2] = m;
                            if (l < i) {
                                c[p >> 2] = k;
                                c[o >> 2] = m;
                                e = m
                            } else {
                                f = d;
                                e = k
                            }
                        } else if (h) {
                            c[p >> 2] = k;
                            c[o >> 2] = e;
                            if (+g[d + 20 >> 2] < i) {
                                c[a >> 2] = d;
                                c[p >> 2] = m;
                                f = j;
                                e = j
                            } else
                                f = j
                        } else {
                            f = d;
                            e = k
                        }
                    while (0);d = c[n >> 2] | 0;
                    if (!(+g[d + 20 >> 2] < +g[f + 20 >> 2])) {
                        a = 1;
                        return a | 0
                    }
                    c[o >> 2] = d;
                    c[n >> 2] = e;
                    e = c[o >> 2] | 0;
                    d = c[p >> 2] | 0;
                    if (!(+g[e + 20 >> 2] < +g[d + 20 >> 2])) {
                        a = 1;
                        return a | 0
                    }
                    c[p >> 2] = e;
                    c[o >> 2] = d;
                    d = c[a >> 2] | 0;
                    if (!(+g[e + 20 >> 2] < +g[d + 20 >> 2])) {
                        a = 1;
                        return a | 0
                    }
                    c[a >> 2] = e;
                    c[p >> 2] = d;
                    a = 1;
                    return a | 0
                }
            case 5:
                {
                    Gd(a, a + 4 | 0, a + 8 | 0, a + 12 | 0, b + -4 | 0, d) | 0;
                    a = 1;
                    return a | 0
                }
            case 1:
            case 0:
                {
                    a = 1;
                    return a | 0
                }
            default:
                {
                    f = a + 8 | 0;
                    n = a + 4 | 0;
                    o = c[n >> 2] | 0;
                    e = c[a >> 2] | 0;
                    q = +g[o + 20 >> 2];
                    i = +g[e + 20 >> 2];
                    d = c[f >> 2] | 0;
                    l = +g[d + 20 >> 2];
                    h = l < q;
                    j = o;
                    k = d;
                    m = e;
                    do
                        if (q < i) {
                            if (h) {
                                c[a >> 2] = k;
                                c[f >> 2] = m;
                                break
                            }
                            c[a >> 2] = j;
                            c[n >> 2] = m;
                            if (l < i) {
                                c[n >> 2] = k;
                                c[f >> 2] = m
                            } else
                                e = d
                        } else if (h) {
                            c[n >> 2] = k;
                            c[f >> 2] = j;
                            if (+g[d + 20 >> 2] < i) {
                                c[a >> 2] = d;
                                c[n >> 2] = m;
                                e = o
                            } else
                                e = o
                        } else
                            e = d;
                    while (0);d = a + 12 | 0;
                    if ((d | 0) == (b | 0)) {
                        a = 1;
                        return a | 0
                    } else {
                        j = e;
                        e = 0
                    }
                    while (1) {
                        h = c[d >> 2] | 0;
                        k = h;
                        if (+g[h + 20 >> 2] < +g[j + 20 >> 2]) {
                            j = h + 20 | 0;
                            h = d;
                            while (1) {
                                c[h >> 2] = c[f >> 2];
                                if ((f | 0) == (a | 0))
                                    break;
                                h = f + -4 | 0;
                                if (+g[j >> 2] < +g[(c[h >> 2] | 0) + 20 >> 2]) {
                                    o = f;
                                    f = h;
                                    h = o
                                } else
                                    break
                            }
                            c[f >> 2] = k;
                            e = e + 1 | 0;
                            if ((e | 0) == 8)
                                break
                        }
                        f = d + 4 | 0;
                        if ((f | 0) == (b | 0)) {
                            d = 1;
                            p = 42;
                            break
                        }
                        o = d;
                        j = c[d >> 2] | 0;
                        d = f;
                        f = o
                    }
                    if ((p | 0) == 42)
                        return d | 0;
                    a = (d + 4 | 0) == (b | 0);
                    return a | 0
                }
            }
            return 0
        }

**Comment by ZfsrGhS953** [comment]
3 more of them. Good luck finding the right one, Mr. Booter-Hatter!
function Ki(b, d, e) {
            b = b | 0;
            d = d | 0;
            e = e | 0;
            var f = 0
              , g = 0
              , h = 0
              , j = 0
              , k = 0
              , l = 0
              , m = 0
              , n = 0;
            n = i;
            i = i + 32 | 0;
            l = n;
            m = n + 8 | 0;
            c[m >> 2] = 0;
            c[m + 4 >> 2] = 0;
            c[m + 8 >> 2] = 0;
            if (!(a[m >> 0] & 1))
                f = 10;
            else
                f = (c[m >> 2] & -2) + -1 | 0;
            qi(m, f, 0);
            h = a[m >> 0] | 0;
            j = m + 1 | 0;
            k = m + 8 | 0;
            g = h;
            h = (h & 1) == 0 ? (h & 255) >>> 1 : c[m + 4 >> 2] | 0;
            while (1) {
                f = (g & 1) == 0 ? j : c[k >> 2] | 0;
                g = l;
                c[g >> 2] = d;
                c[g + 4 >> 2] = e;
                f = Vg(f, h + 1 | 0, 22105, l) | 0;
                if ((f | 0) > -1) {
                    if (f >>> 0 <= h >>> 0)
                        break
                } else
                    f = h << 1 | 1;
                qi(m, f, 0);
                g = a[m >> 0] | 0;
                h = f
            }
            qi(m, f, 0);
            c[b >> 2] = c[m >> 2];
            c[b + 4 >> 2] = c[m + 4 >> 2];
            c[b + 8 >> 2] = c[m + 8 >> 2];
            c[m >> 2] = 0;
            c[m + 4 >> 2] = 0;
            c[m + 8 >> 2] = 0;
            mi(m);
            i = n;
            return
        }
        function Li(b, d, e) {
            b = b | 0;
            d = d | 0;
            e = e | 0;
            var f = 0
              , g = 0
              , h = 0
              , i = 0;
            g = d;
            f = e - g | 0;
            if (f >>> 0 > 4294967279)
                $f(b);
            if (f >>> 0 < 11) {
                a[b >> 0] = f << 1;
                h = b + 1 | 0
            } else {
                i = f + 16 & -16;
                h = bg(i) | 0;
                c[b + 8 >> 2] = h;
                c[b >> 2] = i | 1;
                c[b + 4 >> 2] = f
            }
            b = e - g | 0;
            if ((d | 0) != (e | 0)) {
                f = h;
                while (1) {
                    a[f >> 0] = a[d >> 0] | 0;
                    d = d + 1 | 0;
                    if ((d | 0) == (e | 0))
                        break;
                    else
                        f = f + 1 | 0
                }
            }
            a[h + b >> 0] = 0;
            return
        }
        function Mi(b, d, e) {
            b = b | 0;
            d = d | 0;
            e = e | 0;
            var f = 0
              , g = 0
              , h = 0
              , i = 0;
            h = d;
            f = e - h | 0;
            g = f >> 2;
            if (g >>> 0 > 1073741807)
                $f(b);
            if (g >>> 0 < 2) {
                a[b >> 0] = f >>> 1;
                b = b + 4 | 0
            } else {
                i = g + 4 & -4;
                f = bg(i << 2) | 0;
                c[b + 8 >> 2] = f;
                c[b >> 2] = i | 1;
                c[b + 4 >> 2] = g;
                b = f
            }
            g = (e - h | 0) >>> 2;
            if ((d | 0) != (e | 0)) {
                f = b;
                while (1) {
                    c[f >> 2] = c[d >> 2];
                    d = d + 4 | 0;
                    if ((d | 0) == (e | 0))
                        break;
                    else
                        f = f + 4 | 0
                }
            }
            c[b + (g << 2) >> 2] = 0;
            return
        }

**Comment by MrSonicMaster** [comment]
This chat has become very inactive xd

**Comment by NuclearC** [comment]
lol

probs because everyone left agar bots xD

**Comment by ghost** [comment]
Yes, there are no good free ones anymore XD

**Comment by ghost** [comment]
We could develop one one a github page... I'll make a repo

**Comment by NuclearC** [comment]
no we are not gonna make the protocol public

**Comment by ghost** [comment]
You might not

**Comment by MrSonicMaster** [comment]
Nobody will

**Comment by ghost** [comment]
True, unless that one guy does

**Comment by NuclearC** [comment]
he stopped researching it cuz there is no point... even with the full protocol, you cant bypass captcha

**Comment by ghost** [comment]
I meant someone just might expose it but now that you mention it, captcha seems likely since nobody is making any new breakthroughs

**Comment by MrSonicMaster** [comment]
Feeder bots are trashed, no use in trying to bypass captcha, while its still in effect, bots wont work.

**Comment by ghost** [comment]
Nice.

**Comment by ghost** [comment]
Anyone making an Ogar-based server is gonna get lots more attention

**Comment by MrSonicMaster** [comment]
Anyone who uses or used Ogar-Feeder-Bot was most likely a skid who wanted to feel cool about themselves, so they renamed it and re-released it under their name. I hate ogar-feeder-bot.

**Comment by ghost** [comment]
Yes, what I was saying is Ogar-based servers now have minions, which is now the only source of feeder bots :p

**Comment by MrSonicMaster** [comment]
What games other than agar do people want bots for? My cellcraft bot video got 2x as many views as my agar bot video in half the time...

**Comment by ghost** [comment]
oh wow XD

**Comment by ZfsrGhS953** [comment]
@MrSonicMaster @NuclearC I was researching protocol 9 and was going to make it public, but stopped because I realised that agar is dead. Some clones like petridish or gota have over 2000 players AND are easier to bot. The reason I was going to make it public was not because I wanted to ruin the game, but because bots make the game more interesting, add a lot of new strategies to the game like doublesplitting near the bot owner to block bots from coming, fights that can last more than a few minutes near the bot mouse position when the owner left and forgot to turn bots off and more.

**Comment by NuclearC** [comment]
@ZfsrGhS953 you are right but sadly Moneyshit doesnt understand that :( Even with full protocol we cant bypass captcha.

**Comment by MrSonicMaster** [comment]
Agar.io is dead, even bad clones like Cellcraft, which are easy as all hell to bot, get more people interested in bots than my hard work on agario bots. I personally dont even think gota.io is a good game, I think the physics are bad/rendering is bad.

**Comment by ZfsrGhS953** [comment]
@MrSonicMaster Gota.io was agarp.co before, but Moneyclip sued them and they had to change their name and client, they were developing the client in a hurry.

**Comment by ZfsrGhS953** [comment]
@NuclearC And Barbosik too, that's why I trolled him. I didn't manage to get him triggered though.

**Comment by Barbosik** [comment]
I already implemented high performance native client. 
Also I have web client in beta state, which is faster than vanilla, and has some cool features like sound effects and other.
But I stopped to work on these, due to behavior of some peoples, such as ZfsrGhS953.
I just decided not to publish it and stop to work on it.
Sorry, but this area is no more interesting for me.
Good luck

**Comment by NuclearC** [comment]
@Barbosik alive xD I also made my own client in C++ and it works with Official Servers

**Comment by ZfsrGhS953** [comment]
@NuclearC In case you didn't understand what @Barbosik said:
But I stopped working on it due to people like ZfsrGhS953 trying to keep the game alive.
@Barbosik If you wanted agar to die, why were you working on a client in the first place?

**Comment by MrSonicMaster** [comment]
@Barbosik can you tell me everything you know about 112/113, I already have the protocol, but my method of getting a valid 113 is by using the agario.core.js, which, obviously isn't the best.

**Comment by TheJustExper** [comment]
I found this somehow :D

**Comment by ghost** [comment]
So 0 bots working now, got the gist of this whole conversation.

**Comment by NuclearC** [comment]
@XtremePlayzCODE https://www.youtube.com/watch?v=5G69Foy0O48

**Comment by ghost** [comment]
ಠ_ಠ

**Comment by ghost** [comment]
i want ༼ つ ಥ_ಥ ༽つ

**Comment by MrSonicMaster** [comment]
11181

**Comment by ghost** [comment]
Umm... Right... Wut?

**Comment by ghost** [comment]
Like the gene treh trehalase?

**Comment by MrSonicMaster** [comment]
No, do 
```(11181).toString(16)```
in console

**Comment by ghost** [comment]
Agar console?

**Comment by ghost** [comment]
Wellp.

**Comment by ghost** [comment]
I got string'ed.

**Comment by MrSonicMaster** [comment]
xD

**Comment by ghost** [comment]
Do you know why I have bruise-like marks on BandAid-covered spots after falling down the stairs and getting bad scrapes?

**Comment by ghost** [comment]
@ZfsrGhS953 Can you add me on skype ? I have some interresing info for you.

My skype : lefela4

**Comment by NuclearC** [comment]
@lefela4 stfu :D

**Comment by ghost** [comment]
@NuclearC Dude...

**Comment by MrSonicMaster** [comment]
xd what interesting info

**Comment by ghost** [comment]
@MrSonicMaster Something ^^

**Comment by ghost** [comment]
@ZfsrGhS953 Are you active ? I need to talk to you fast ! My skype is : lefela4

**Comment by NuclearC** [comment]
He dosnt have skype @lefela4

**Comment by ghost** [comment]
@ZfsrGhS953 Then can you contact me whit email? My email is : slithervipbot@gmail.com Thx !

**Comment by NuclearC** [comment]
no he cant

**Comment by ghost** [comment]
why not ?

**Comment by mbm3** [comment]
@lefela4 cause ur pleb

**Comment by TheJustExper** [comment]
@lefela4 Because its g.tk

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
oshit this is still happening

**Comment by NuclearC** [comment]
XD ikr

**Comment by ghost** [comment]
this isn't even about packets now

**Comment by ghost** [comment]
close issue

**Comment by ghost** [comment]
NO dont ! I will

**Comment by ghost** [comment]
._.

**Comment by ghost** [comment]
Someone can tell me if agar use aes ?

**Comment by NuclearC** [comment]
yes it uses aes encryption

**Comment by DaAwesomeRazor** [comment]
@NuclearC hes trying to trick you agar uses SHA678 hash, and the secret is in 254 packet

**Comment by ghost** [comment]
SHA678 dosen't exist, what if you're tricking us?

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
I cant find SHA678 in npm

**Comment by ghost** [comment]
maybe SHA256?

**Comment by ghost** [comment]
and it no even packet 254..

**Comment by ghost** [comment]
@NuclearC what they use for the decryption ._.

**Comment by ghost** [comment]
@DaAwesomeRazor Dude SHA678 it SHA256 X3. It not possible. The packet 254 dont existe

**Comment by ghost** [comment]
He's tryna trick you

**Comment by NuclearC** [comment]
no he isnt

**Comment by ghost** [comment]
now i am confused, @XtremePlayzCODE what they use for the decryption?

**Comment by NuclearC** [comment]
@Sonicmaster13 close this????

**Comment by ghost** [comment]
Do not close this issu. Nuclear and Sonic just want them to have wroking agar.io bots. Do not close it. Guys we need to work together and make agar.io bots. I have fixed everything before agar add the packet scrambeling when you connect. To have working bots, I need to know what is the decryption they use. So if we want bots back, tell me what they use for the decryption and the encryption.

**Comment by ghost** [comment]
The hope...

**Comment by ghost** [comment]
@Sonicmaster13 Do not close it

**Comment by ghost** [comment]
I just found some interresing info, It seam to be a hash function generator and a unique UUID generator. Maybe it could make something in the core...

**Comment by Sonicmaster13** [comment]
Off topic, issue solved, closing issue.

**Comment by TheJustExper** [comment]
gggaayy

**Comment by ghost** [comment]
Oh no!

**Comment by ghost** [comment]
https://github.com/xzfc/agar-expose/issues/38

**Comment by DaAwesomeRazor** [comment]
@Sonicmaster13 ruined the fun

**Comment by MrSonicMaster** [comment]
lol

**Comment by NuclearC** [comment]
lmfao who's still alive?

**Comment by ghost** [comment]
not me

**Comment by MrSonicMaster** [comment]
lol

**Comment by ghost** [comment]
i died

**Comment by Barbosik** [comment]
@MrSonicMaster can you tell me everything you know about 112/113

112 was used as auth reqeuest to check if a client is valid. 113 is response for that.
It was calculated with SHA1 and the key which can be extracted from core.js.
But they stopped to using this packet long time ago.
With protocol 14, which rolled out last days, they removed the code for these things.

Now they using message 85 to request google captcha, the response should be send with message 86.

**Comment by NuclearC** [comment]
@Barbosik any way we can contact you? (skype/discord)

**Comment by Barbosik** [comment]
You can contact me with email, but I will not give you protocol details.
I talked it previously, if you will use bots they will change protocol continuously.
Agario developers stated it pretty clear. They allowed you to use your own clients and even turned a blind eye to a little amount of bots. But they asked to not use it for mass bots.

All these bot developers ruined that equilibrium and ruined alternative clients.
I talked about it before, but no one listen to me, they talked that they are smart and it's impossible to prevent bots. And now we have results.

The protocol is not so hard, and still can be used for alternative clients. But I think if it will be published, it will be used by botters and it will ruined again in 1-2 weeks. And again, you will need to spend the time to research the new protocol, just to play some time with ur own client.

**Comment by NuclearC** [comment]
@Barbosik we already have the whole protocol and its already published

**Comment by ghost** [comment]
published? where

**Comment by DaAwesomeRazor** [comment]
@XtremePlayzCODE Check out my repository

**Comment by DaAwesomeRazor** [comment]
If anyone here claims to be an agarplus developer they are lieng dont believe them

**Comment by henopied** [comment]
@Barbosik it really hasn't change much in the last year or so. I am a developer of agarplus v3 which is a custom client from scratch using esnext and a modern webpack build system. You can check for verification on the agarplus menu screen. If you would like to get in contact you can message me on skype:henopied discord:Henopied#6298.

**Comment by DaAwesomeRazor** [comment]
@henopied @Barbosik what did I say....

**Comment by MrSonicMaster** [comment]
I am an agArPlus DevElOpeR and I hVae ProtOCOl!!11

**Comment by ghost** [comment]
true

**Comment by ghost** [comment]
true

**Comment by ghost** [comment]
It published in sonic pc.

**Comment by MrSonicMaster** [comment]
yes

**Comment by ghost** [comment]
Ik

**Comment by ghost** [comment]
o ok

**Comment by Barbosik** [comment]
@NuclearC: published? where? I'm interesting what is the meaning of extended flags in the cell update packet which was added in the protocol 14? At a glance it looks like some kind of player ID, related with the new leaderboard packets. But I'm not sure...

**Comment by NuclearC** [comment]
@Barbosik: can you give me your email?
